#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "f2bwiphp"
name = "Fail2Ban Webinterface PHP"
description.en = "Monitor fail2ban and manually ban / release IP's"
description.fr = "Monitorer fail2ban et bannir ou dé-bannir des IP's"

version = "1.0~ynh1"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0-or-later"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/ewilly/fail2ban-web-interface-php"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/f2bwiphp"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/ewilly/fail2ban-web-interface-php/archive/refs/tags/v1.1.zip"
        sha256 = "8e8fe3a113fe7ef1d4472691a29108dcfa8e3a4247b40c7e317cd415ca2b7655"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "fail2ban, php8.3-fpm"
